### ISSUE TITLE
Data storage 

### ISSUE THREAD

**Issue by patrickpierson** [joinrobin/robin#1]
Since you are using reddit oauth do you really need a data store? If you are storing what users are saying then ok have a store but I don't think you want to do that. 

Maybe you want to store room info? I would say no as well because the rooms are temporary until another right sized room is found and merged.

Just some thoughts I had on the data side. Close if you want to.

**Comment by IeuanG** [comment]
I'd suggest redis for the storage, as it's temporary anyway.

**Comment by kevwu** [comment]
We're kind of on the fence about using reddit oauth. We might just let users set their username when they join and then identify them by session/secure cookie.

For now we're going to store chat history in memory (so it's ephemeral); if we implement persistent chat that'll be later down the line. (And redis is being considered for the data store if we do.)

Thanks for your input!
