### ISSUE TITLE
[Security] Inputs not being sanitized

### ISSUE THREAD

**Issue by 5a1t** [joinrobin/robin#4]
Site is vulnerable to XSS via text input.

Let me know if you'd like an attack example privately.

**Comment by Sxw1212** [comment]
Can you email the details to sam@fluidnode.com? I'll check it out later today. Thanks.

**Comment by xSke** [comment]
Can confirm. 

![](http://i.imgur.com/cKXhDmI.png)

![](http://i.imgur.com/4dw1dHv.png)

**Comment by Sxw1212** [comment]
Fixed.
