### ISSUE TITLE
Come say hi to the Parrot team

### ISSUE THREAD

**Issue by Annon201** [joinrobin/robin#5]
Come join us in https://gitter.im/5a1t/parrot and say hi. :+1:

**Comment by Stjerneklar** [comment]
yeah, by our powers combined and all that :D

**Comment by LewisMCYoutube** [comment]
I hope you resolve this issue. It has been bothering me a lot.
**:-(**

**Comment by Stjerneklar** [comment]
you could phrase it as "You guys don't have any way to contact you listed, got a gitter?"

**Comment by Sxw1212** [comment]
We have a slack

**Comment by hatrick-patrick** [comment]
Could I suggest that ye don't implement Parrot as the default Canary UI, but rather adapt the various plugins to fit Canary just like they did with Robin?

One of the cool things on Robin (IMO anyway) was the fact that Reddit just gave us the bare chat interface, and everyone's experience of it was coloured entirely by which plugins they chose to use. Some users never installed any and simply revelled in the chaos, others installed every plugin under the sun and had an entirely different Robin experience, which was part of the fun in my view...

**Comment by Annon201** [comment]
Just trying to unite the dev teams from Robin for the moment to share ideas for whats next.

**Comment by Annon201** [comment]
@Stjerneklar could you branch the project so I can make a local copy of the issue with the correct wording?

**Comment by Sxw1212** [comment]
Invited most people from parrot gitter to the robin-dev slack. Open an issue / send a message to sam@fluidnode.com for an invite.
