### ISSUE TITLE
Password phishing operation.

### ISSUE THREAD

**Issue by dashed** [joinrobin/robin#9]
It has come to my immediate attention that http://joinrob.in/ is potentially as password phishing operation; as the site is not, at all, functional; regardless of whether or not you, the developers, have good intentions or not.

-----

I've taken steps to warn former users of Robin to not re-use password and even change their passwords. 

I suggest taking down http://joinrob.in/ until it is ready for production.

**Comment by Hipe99** [comment]
Evidence includes the fact that everyone there is called wargg, wtmh or sandlehat.

**Comment by Lolzep** [comment]
I agree, its really fishing registering for it and then having nothing to register for.

**Comment by dashed** [comment]
In addition, there is no way to prove that the code on http://joinrob.in/  (the production) is the same code in this repository.

**Comment by RenegadeAI** [comment]
Well its not, this repo is no longer used

**Comment by Sxw1212** [comment]
NEWS ALERT!!! GOOGLE COULD STEAL YOUR PASSWORDS AND USE THEM ON OTHER SITES! WARNING!

Seriously though, this is a risk with every site, and we're working on integrating reddit authentication.

**Comment by dashed** [comment]
@RenegadeAI  @Sxw1212 totally unprofessional response; I'm disappointed in you guys.

**Comment by RenegadeAI** [comment]
I'm not a professional, we don't want people using the site yet, we aren't asking you to put your password in.

Heck, I'm not even using my own password on it.

**Comment by Sxw1212** [comment]
1. You're in our Slack chat. You can clearly see that we're not running a phishing operation. I consider it rather rude that you just come here and say that we're stealing information.
2. Any internet site is potentially a phishing operation. 
3. If people who used this get their account stolen, then you know. But, I do not store plaintext passwords, and it will not happen unless they use their password somewhere else. 
4. The users on the side are placeholders, we have user listing in progress on the other repository, which is at https://github.com/JoinRaven/Raven

**Comment by dashed** [comment]
you do not fucking put a non-functional app into production!

**Comment by RenegadeAI** [comment]
Its not in prod

**Comment by xereeto** [comment]
unprofessional? you do realize we're a bunch of guys working on some reddit project, not a fortune 500 company? also, it's not in production.

**Comment by Sxw1212** [comment]
That is a beta site, for beta testing.

**Comment by dashed** [comment]
Call it what you want. Users can seem to register.

**Comment by Sxw1212** [comment]
Yes, because that is part of the functionality we are beta testing.

**Comment by xereeto** [comment]
Yeah no shit, we're testing registering functionality

**Comment by dashed** [comment]
Please; I implore you to take it down or close it off as a testing ground from ***public view***.

**Comment by dashed** [comment]
Guys... this is SaaS-webdev-101.

**Comment by Sxw1212** [comment]
We're running this app with a number of security features. It supports TLS and passwords are hashed with bcrypt before storage in the backend.

**Comment by dashed** [comment]
*sighs* @Sxw1212 

>In addition, there is no way to prove that the code on http://joinrob.in/ (the production) is the same code in this repository.

**Comment by Sxw1212** [comment]
There is no way to prove that the code on google.com doesn't store your passwords.

**Comment by dashed** [comment]
The best compromise you could do is this: https://github.com/joinrobin/robin/issues/9#issuecomment-207919822

And you don't seem to agree....

**Comment by xereeto** [comment]
it's not the same code in this repository. _this is an unused repo._

**Comment by RenegadeAI** [comment]
I agree that it may not be the smartest thing to have it live, but its not like we are going around advertising it everywhere, there's some other guy that's doing that, and its kind of a pain.

**Comment by dashed** [comment]
Users don't care... the site is ***still non-functional after registration***; which is very suspicious!

**Comment by xereeto** [comment]
suspicious of fucking what? we haven't released the damn thing yet

**Comment by Wulfre** [comment]
Can confirm, I'm not suspicious.

**Comment by xereeto** [comment]
if you sign up for non-released software and get 'suspicious' because it doesn't work, you're retarded

**Comment by Sxw1212** [comment]
The last time I checked, users were able to merge with another after voting grow. I suspect that this is currently broken, but chat exists. Would you like me to move you into the same room from our backend?

**Comment by dashed** [comment]
so you're not going to do anything about this issue?

**Comment by dashed** [comment]
this is a glaring security issue.

**Comment by dashed** [comment]
it doesn't matter if you use bcrypt or your favourite modern hash and salt combo.

**Comment by Sxw1212** [comment]
How do you suggest we secure passwords?

**Comment by dashed** [comment]
CLOSE THE SITE OFF FROM PUBLIC VIEWING UNTIL IT'S FUNCTIONAL!

**Comment by Sxw1212** [comment]
But after we release it, we could still steal passwords. How do you suggest we fix that?

**Comment by dashed** [comment]
@Sxw1212 please look at the now instead of the future. https://github.com/joinrobin/robin/issues/9#issuecomment-207920961

**Comment by Sxw1212** [comment]
Any user serious about security is welcome to use a different password for this site, like they are for any site. I'm sorry that you don't see the use of a hosted beta application, and you're welcome to host an instance yourself if you want to play with it without any risk of passwords being stolen.

**Comment by Sxw1212** [comment]
If you wish to continue this conversation, we are at joinrobin.slack.com. You are in our list of members.

**Comment by xereeto** [comment]
@dashed http://joinrob.in <---- happy now? we've moved it to dev.joinrob.in

**Comment by dashed** [comment]
Thank you. That wasn't so hard was it?

**Comment by RenegadeAI** [comment]
Making the web a safer place, one domain at a time.
